name: AI Code Review

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Open Code Review
    steps:
      - uses: alibaba/open-code-review@v1.7.17
        with:
          llm_url: https://token-plan-cn.xiaomimimo.com/v1
          llm_auth_token: ${{ secrets.CHAT_TOKEN }}
          llm_model: mimo-v2.5-pro
          llm_use_anthropic: 'false'
          language: '中文'
